# Generated by Django 3.1.5 on 2021-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Desription', models.CharField(max_length=200, null=True)),
                ('Instructor', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('Date', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/unit_pics')),
                ('unit_no', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(choices=[('Inservice', 'Inservice'), ('OOS', 'OOS')], default='Inservice', max_length=20)),
                ('Problem', models.CharField(max_length=200, null=True)),
                ('Notified', models.CharField(choices=[('EMA 1', 'EMA 1'), ('EMA 3', 'EMA 3'), ('EMA 4', 'EMA 4'), ('EMA 5', 'EMA 5'), ('N/A', 'N/A')], default='N/A', max_length=200)),
                ('Date', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(choices=[('Station 1', 'Station 1'), ('Station 2', 'Station 2'), ('Station 3', 'Station 3'), ('Station 4', 'Station 4'), ('Fleet Matenance', 'Fleet Matenance')], default='Station 1', max_length=20, null=True)),
            ],
        ),
    ]
